version: '3'

networks:
  app-network:
    driver: bridge

services:
  app:
    build:
      context: ..
      dockerfile: dev.Dockerfile

    networks:
      - app-network

    volumes:
      - ..:/workspaces/container-app-example-python:cached

    command: sleep infinity
